# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
    autoload: false
    plugins:
        specialchar:
            path:     "/build/ckeditor/plugins/specialchar/" # with trailing slash
            filename: "specialchar.js"
        quoteplugin:
            path:     "/build/ckeditor/plugins/quoteplugin/"
            filename: "plugin.js"
        bbcode:
            path:     "/build/ckeditor/plugins/bbcode/"
            filename: "plugin.js"
    default_config: common_config
    configs:
        common_config: &config
            extraPlugins: ["quoteplugin"]
            removePlugins: ["exportpdf", "easyimage", "cloudservices" ]
            toolbar: [ [ 'CreateDiv', 'Bold', 'Italic', 'Link', 'Quoteplugin', 'SpecialChar', 'RemoveFormat', 'Source' ] ]
            specialChars: [ '…', '–', '×', '«', '»', '“', '”', '‘', '’', 'ї', '', '|im.|', '|vac.|', 'Ѡ', 'Ѿ', 'Ѻ', 'Ꙩ', 'Ѧ', 'Ѩ', 'Ѫ', 'Ѭ', 'Ѣ', 'Ѯ', 'Ꙗ', 'Ꙋ', 'Ѳ', 'І', 'Є', 'Ѥ', 'Ѕ', 'Ѵ', 'Ѱ', 'Ꙑ', 'ѡ', 'ѿ', 'ѻ', 'ꙩ', 'ѧ', 'ѩ', 'ѫ', 'ѭ', 'ѣ', 'ѯ', 'ꙗ', 'ꙋ', 'ѳ', 'і', 'є', 'ѥ', 'ѕ', 'ѵ', 'ѱ', 'ꙑ', '⁙', '҂', '|', '¦', '⸗', '҃', '҇', '·', '→', '⃝' ]
        textconfig:
            <<: *config
            extraPlugins: ['bbcode']
            toolbar: [ [ 'SpecialChar', 'Source', 'RemoveFormat' ] ]
        searchconfig:
            <<: *config
            removePlugins: ["exportpdf", "easyimage", "cloudservices", "elementspath", "resize" ]
            extraPlugins: ['bbcode']
            toolbar: [ [ 'SpecialChar' ] ]
            height: "32px"
            contentsCss: [ '/build/ckeditor/custom.css' ]
            toolbarLocation: "bottom"
            toolbarCanCollapse: true
            toolbarStartupExpanded: false
            stylesSet: 'mystile'
    styles:
        mystile:
            - { name: "text", element: "span", styles: { font-family: 'Arial, Helvetica, sans-serif' } }
            - { name: "othertext", element: "p", styles: { font-family: 'Arial, Helvetica, sans-serif' } }



