# This file is part of «Epigraphy of Medieval Rus» database.
#
# Copyright (c) National Research University Higher School of Economics
#
# «Epigraphy of Medieval Rus» database is free software:
# you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, version 3.
#
# «Epigraphy of Medieval Rus» database is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code. If you have not received
# a copy of the GNU General Public License along with
# «Epigraphy of Medieval Rus» database,
# see <http://www.gnu.org/licenses/>.

monolog:
  handlers:
    warnings_filter:
      type: fingers_crossed
      action_level: warning
      handler: warnings
      excluded_http_codes: [404, 405]
      buffer_size: 500
    warnings:
      type: rotating_file
      path: '%kernel.logs_dir%/%kernel.environment%.warning.log'
      level: debug
      max_files: 7
    errors_filter:
      type: fingers_crossed
      action_level: error
      handler: errors
      excluded_http_codes: [404, 405]
      buffer_size: 500
    errors:
      type: rotating_file
      path: '%kernel.logs_dir%/%kernel.environment%.error.log'
      level: debug
      include_stacktraces: true
      max_files: 7
    console:
      type: console
      process_psr_3_messages: false
      channels: ['!event', '!doctrine']
